export const APP_ROUTES = {
  home: "/",
  about: "/ve-chung-toi",
  contact: "/lien-he",
  quote: "/bao-gia",
  products: "/san-pham",
  productDetail: (slug: string) => `/san-pham/${slug}` as const,
  projects: "/du-an",
  projectDetail: (slug: string) => `/du-an/${slug}` as const,
  blog: "/blog",
  blogPost: (slug: string) => `/blog/${slug}` as const,
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    products: "/admin/san-pham",
    productCreate: "/admin/san-pham/them-moi",
    productEdit: (id: string) => `/admin/san-pham/${id}/chinh-sua` as const,
    posts: "/admin/bai-viet",
    postCreate: "/admin/bai-viet/them-moi",
    postEdit: (id: string) => `/admin/bai-viet/${id}/chinh-sua` as const,
    projects: "/admin/du-an",
    projectCreate: "/admin/du-an/them-moi",
    projectEdit: (id: string) => `/admin/du-an/${id}/chinh-sua` as const,
    leads: "/admin/leads",
    leadDetail: (id: string) => `/admin/leads/${id}` as const,
    media: "/admin/media",
    settings: "/admin/cai-dat",
    users: "/admin/cai-dat/nguoi-dung",
    system: "/admin/cai-dat/he-thong",
  },
} as const;
